---
- name: Install NewRelic agents.
  hosts: servers
  remote_user: "{{ remote_user }}"
  become: yes
  become_method: sudo
  roles:
    - common
    - newrelic-java-agent
    - newrelic-infrastructure-agent
    - ohi-mysql
    - deployment-java
